initial version

diff --git a/kubernetes/jenkins/Dockerfile.jenkins_slave_docker b/kubernetes/jenkins/Dockerfile.jenkins_slave_docker
--- a/kubernetes/jenkins/Dockerfile.jenkins_slave_docker
+++ b/kubernetes/jenkins/Dockerfile.jenkins_slave_docker
@@ -1,27 +1,31 @@
-FROM jenkins/jnlp-slave:alpine
-
-ARG JENKINS_URL
-ARG JENKINS_SECRET
-ARG JENKINS_HOME="/home/jenkins"
-
-ARG DOCKER_VERSION=17.10.0-ce
-
-ARG AGENT_VERSION=3.10
-ARG AGENT_WORKDIR=/home/jenkins/agent
-
-ENV JENKINS_HOME=${JENKINS_HOME} \
-    AGENT_WORKDIR=${AGENT_WORKDIR} \
-    DOCKER_VERSION=${DOCKER_VERSION}
-
+FROM jenkinsci/jnlp-slave:alpine
 USER root
-RUN apk add --update --no-cache curl \
-                                ca-certificates && \
-    addgroup -g 1000 -S docker && \
-    addgroup jenkins docker && \
-    addgroup jenkins ping
-
-# Install Docker
-RUN curl -fL -o docker.tgz https://download.docker.com/linux/static/edge/x86_64/docker-${DOCKER_VERSION}.tgz && \
-	tar -xzf docker.tgz -C /usr/local/bin/ --strip-components=1  && \
-	rm docker.tgz
-
+RUN apk add --no-cache \
+        ca-certificates
+ENV DOCKER_CHANNEL stable
+ENV DOCKER_VERSION 17.03.1-ce
+RUN set -ex; \
+    apk add --no-cache --virtual .fetch-deps curl tar ; \
+    apkArch="$(apk --print-arch)"; \
+    case "$apkArch" in \
+        x86_64) dockerArch='x86_64' ;; \
+        *) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+    esac; \
+  \
+    if ! curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
+        echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
+        exit 1; \
+    fi; \
+  \
+    tar --extract \
+        --file docker.tgz \
+        --strip-components 1 \
+        --directory /usr/local/bin/ \
+    ; \
+    rm docker.tgz; \
+    \
+    apk del .fetch-deps; \
+    \
+    dockerd -v; \
+    docker -v
+USER jenkins
